server:
  port: 8090
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  thymeleaf:
    enabled: true
    encoding: UTF-8
    prefix: classpath:/templates/
    suffix: .html
    cache: false

  datasource:
    url: jdbc:mariadb://localhost:3306/myblog?characterEncoding=UTF-8
    driver-class-name: org.mariadb.jdbc.Driver
    username: pjb
    password: jb641954

  jpa:
    hibernate:
      ddl-auto: update #create update none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true